## variable file ##
## DEPLOYMENT  ##
name: "eks-app"
namespace: "eks"
labels:
   app: "eks-app"
replicas: 2
selector:
    matchLabels:
       app: "eks-app"
containers:
   name: "eks-app"
   image: test
containerPort: 80

##  Horizontal Pod Autoscaling  ##
hpa:
 name: "eks-app-hpa"
 maxReplicas: 4
 minReplicas: 2
 cpu:
    averageUtilization: 80
 memory:
    averageUtilization: 80

## SERVICE ##  
service:
   name: "eks-app-service"
   type: LoadBalancer
   port: 80
   targetPort: 80
